# Generated by Django 2.0.4 on 2018-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180421_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestpoint',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
