# Generated by Django 2.0.4 on 2018-04-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180421_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
