# Generated by Django 2.0.2 on 2018-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180421_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestpoint',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestpoint',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contests',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='question',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='question',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='ContestPoint',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
